---

- name: Install epel-release
  become: true
#  become_method: su
  ansible.builtin.yum:
    name: epel-release
    state: present

- name: Install nginx
  become: true
#  become_method: su
  ansible.builtin.yum:
    name: nginx
    state: present
    disable_gpg_check: yes # package is not signed
  notify:
    - Restart nginx

- name: Install git
  become: true
#  become_method: su
  ansible.builtin.yum:
    name: git
    state: present
    disable_gpg_check: yes

- name: Create folder for lighthouse
  become: true
#  become_method: su
  ansible.builtin.file:
    path: /usr/share/nginx/lighthouse
    state: directory
    mode: '0755'

- name: Copy lighthouse config to nginx
  become: true
#  become_method: su
  ansible.builtin.template:
    src: "{{ lighthouse_template }}"
    dest: "{{ lighthouse_config_file }}"
    mode: 0644
  notify: Restart nginx

- name: Install lighthouse
  become: true
#  become_method: su
  ansible.builtin.git:
    repo: https://github.com/VKCOM/lighthouse
    dest: /usr/share/nginx/lighthouse
    clone: yes
    update: yes
  notify:
    - Restart nginx
